sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t 75017864/multidocker -f ./client/Dockerfile.dev ./client
scripts:
  - docker run 75017864/multidocker npm test -- --coverage
after_success:
  - docker build -t 75017864/multi-client ./client
  - docker build -t 75017864/multi-nginx ./nginx
  - docker build -t 75017864/multi-server ./server
  - docker build -t 75017864/multi-worker ./worker

  # take images and push to docker hub
  - echo "$PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  75017864/multi-worker
  - docker push  75017864/multi-server
  - docker push  75017864/multi-nginx
  - docker push  75017864/multi-client
deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-1-831924411927"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"